### ISSUE TITLE
Test and update CK-MLPerf-BERT workflow from Thomas

### ISSUE THREAD

**Issue by gfursin** [octoml/mlops#5]

**Comment by gfursin** [comment]
I integrated Thomas' update to our mainline but there is some issue. @hanwenzhu can you please report here.

**Comment by hanwenzhu** [comment]
Problem: the `vocab.txt` is not included in build dir: https://github.com/octoml/mlops/commit/247043f2ccfabdac994a486ccc711e5ce20f48b2#diff-383c5197bad85ffc0b41631f89c5c37d587f3af85a984b9d906642421f0c4cb5 ignores `vocab.txt` so the program fails.

Fix: revert + prune `build` every time the script is run. See patch here: https://github.com/hanwenzhu/mlops/tree/bert-patch

**Comment by gfursin** [comment]
I believe I fixed it: https://github.com/mlcommons/ck-mlops/commit/07f45fea3360d5b167061275b7fcfd657d78f2f4 .
Thanks, Thomas!
We just need to update README to add deps on Transformers, PyTorch and TF ...

**Comment by gfursin** [comment]
I updated docs with dependencies and added transformers docs: https://github.com/mlcommons/ck-mlops/tree/main/program/mlperf-inference-bench-language-onnx-cpu .
I am closing this ticket.
