### ISSUE TITLE
Add CK meta-package to install TVM via PIP

### ISSUE THREAD

**Issue by gfursin** [octoml/mlops#6]
The current [CK automation package for TVM](https://github.com/octoml/mlops/tree/main/package/compiler-tvm-from-src) builds TVM from sources. We need to add CK package to install TVM nightly builds via PIP (https://tlcpack.ai) to test them with our [CK MLPerf workflows](https://github.com/octoml/mlops/tree/main/program).

**Comment by gfursin** [comment]
As suggested by @hogepodge .

**Comment by gfursin** [comment]
CC @hanwenzhu .

**Comment by gfursin** [comment]
Examples are here: https://tlcpack.ai/

**Comment by tmoreau89** [comment]
@gfursin I'm trying to understand the context here - is the motive that for MLPerf to accept our submission we should be installing TVM via pip?

**Comment by hogepodge** [comment]
I wasn't entirely sure of the context behind the CK project, and was thinking more along the lines of how collab is integrated with TVM and how new users would approach it. Being able to abstract away the building process and allow for package installation allows for a better user experience. I can't speak to if it's appropriate for the MLPerf project and process.

**Comment by gfursin** [comment]
Hey @tmoreau89 - no, we do not need it for MLPerf submissions right now and it's not urgent. 

Indeed, we want to show how we abstract away the TVM installation process from (CK) workflows while using MLPerf as a practical use case because I am working on it right now ;) . 

I provided a CK automation to build TVM from sources and plug it into MLPerf workflows, however it may take 20..30 min to complete in Colab. End-users may want to install TVM via PIP rather than building it - that's why we thought to add a related CK automation just to a) speed up this demo b) show how workflows can help to abstract away the TVM building and installation process.

**Comment by gfursin** [comment]
By the way, note that CK packages are meta packages, i.e. these are just a collection of automation recipes to install different versions of different tools across different operating systems and hardware in a unified way while abstracting them from the high-level tasks and workflows.

**Comment by gfursin** [comment]
I close this issue because we will be developing new meta packages within the CK2 framework.
